In [1]:
from keras.preprocessing.image import img_to_array
from PIL import Image
import numpy as np
import os

/opt/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
! pip install imutils

In [3]:
from imutils import paths

In [4]:
a={'dent':0, 'leeton':1, 'pimple':2, 'residual':3, 'scratch_M':4, 'spot_M':5, 'foreign':6,\
   'longscratch_M':7, 'pinhole':8, 'scratch':9, 'spot':10, 'wrinkle':11}

In [5]:
os.getcwd()

'/home/jovyan/Vivian_1070926/Yunzy/training_code'

In [12]:
os.chdir('/home/jovyan/Vivian_1070926/Yunzy/model_save')

In [9]:
from keras.models import load_model
model = load_model('7th.h5')

In [13]:
os.chdir('/home/jovyan/Vivian_1070926/Yunzy')

In [14]:
data=[]
imagePaths = sorted(list(paths.list_images("./sep_pic/aug")))
for imagePath in imagePaths:
    label = imagePath.split(os.path.sep)[4] 
#     print(imagePath)
#     print(label)
    if label[0] == ".":
        print(imagePath)
        os.remove(imagePath) 
        print(os.path.exists(imagePath))
        continue
    print(imagePath)
    image = Image.open(imagePath)
    image = image.resize((100, 100))
    image = img_to_array(image)
    data.append(image)

./sep_pic/aug/aa/1261504-10405-20180110_00004.bmp
./sep_pic/aug/aa/1261504-10405-20180110_00005.bmp
./sep_pic/aug/aa/1261504-10405-20180110_00006.bmp
./sep_pic/aug/aa/1261504-10405-20180110_00007.bmp
./sep_pic/aug/aa/1261504-10405-20180110_00008.bmp
./sep_pic/aug/aa/1261504-10405-20180110_00033.bmp
./sep_pic/aug/aa/1261504-10405-20180110_00034.bmp
./sep_pic/aug/aa/1261504-10405-20180110_00036.bmp
./sep_pic/aug/aa/1261504-10405-20180110_00037.bmp
./sep_pic/aug/aa/1261504-10405-20180110_00056.bmp
./sep_pic/aug/aa/1261504-10405-20180110_00058.bmp
./sep_pic/aug/aa/1261504-10405-20180110_00089.bmp
./sep_pic/aug/aa/1261504-10405-20180110_00100.bmp
./sep_pic/aug/aa/1261504-10405-20180110_00361.bmp
./sep_pic/aug/aa/1261504-10405-20180110_00506.bmp


In [15]:
data=np.array(data)/255
data.shape

(15, 100, 100, 3)

In [24]:
prediction = model.predict(data)
prediction[0]

array([1.5875220e-12, 7.4830080e-20, 6.8009004e-10, 3.1620380e-13,
       4.1157377e-13, 2.4535354e-13, 3.0677951e-12, 1.9474856e-12,
       9.9999928e-01, 1.5870177e-14, 4.2492814e-15, 7.4690826e-07],
      dtype=float32)

In [26]:
pred_label = np.argmax(prediction, axis=1)
pred_label

array([ 8,  8,  8,  8,  8, 11, 11, 11, 11,  1,  1,  1,  1,  1, 11])

In [21]:
prediction = model.predict_classes(data)
prediction

array([ 8,  8,  8,  8,  8, 11, 11, 11, 11,  1,  1,  1,  1,  1, 11])